services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
      - BOT_API_URL=http://music_bot:5050/share-video
      - BASE_URL=https://umkgl.online 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "D:/weboldal fájlok:/usr/src/app/public/uploads"
    networks:
      - umgkl_net
      - shared_proxy_net
      - umkgl-network
      
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - "D:/weboldal fájlok/adatbazis:/var/lib/postgresql/data"
    networks:
      - umgkl_net

networks:
  umgkl_net:
  shared_proxy_net:
    external: true
    
  umkgl-network:
    external: true  
