services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "D:/weboldal fájlok:/usr/src/app/public/uploads"
    networks:
      - umgkl_net
      - shared_proxy_net

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:                 # <--- EZT KELL HOZZÁADNI A SERVICE VERZIÓHOZ
      - "5432:5432"        # <--- HOGY A DBEAVER LÁSSA
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - "D:/weboldal fájlok/adatbazis:/var/lib/postgresql/data"
    networks:
      - umgkl_net

networks:
  umgkl_net:
  shared_proxy_net:
    external: true