services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - umgkl_net
      - shared_proxy_net

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    # EZ A RÃ‰SZ NYITJA KI A PORTOT A DBeavernek
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - umgkl_net

volumes:
  postgres_data:

networks:
  umgkl_net:
  shared_proxy_net:
    external: true